version: '3.8'

services:
  nodejs-app:
    build: .
    ports:
      - "5006:5006"
    depends_on:
      - mysql
    environment:
      - PORT=5006
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=sql_login
    restart: always

  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: sql_login
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: P@ssw0rd
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: